---
- name: Apt cache updated
  apt: update_cache=yes

- name: Nginx is installed
  apt:
    name: nginx
    state: present

- name: ensure known hosts
  file:
    path: /home/ubuntu/.ssh/known_hosts
    owner: ubuntu
    group: ubuntu
    state: touch
    mode: 0644

- name: setup group for root of web roots
  group:
    name: www-data
    state: present

- name: set group and mode for root of web roots
  file:
    path: /usr/share/nginx/html
    group: www-data
    mode: 0775

- name: add ubuntu to www-data group
  user:
    name: ubuntu
    state: present
    groups: www-data
    append: yes
