---
- include_tasks: setup-Debian.yml
  when:
    - ruby_install_from_source == False
    - ansible_os_family == 'Debian'

# Install ruby from source when ruby_install_from_source is true.
- include_tasks: install-from-source.yml
  when: ruby_install_from_source == True

# Install Bundler and configured gems.
- name: Install Bundler.
  gem: name=bundler state=present user_install=no
  when: ruby_install_bundler

- name: Install jekyll
  command: gem install jekyll --no-rdoc --no-ri
