---
----
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ruby_install_from_source == False

- name: Install ruby, rubygems, and build-essential.
  apt: "name={{ item }} state=present"
  with_items:
    - ruby-full
    - ruby-dev
    - "{{ ruby_rubygems_package_name }}"
    - build-essential
  when: ruby_install_from_source == False

# Install ruby from source when ruby_install_from_source is true.
- include_tasks: install-from-source.yml
  when: ruby_install_from_source == True

# Install Bundler and configured gems.
- name: Install Bundler.
  gem: name=bundler state=present user_install=no
  when: ruby_install_bundler

- name: Install jekyll
  command: gem install jekyll --no-rdoc --no-ri
