---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install ruby, rubygems, and build-essential.
  apt: "name={{ item }} state=present"
  with_items:
    - ruby-full
    - ruby-dev
    - "{{ ruby_rubygems_package_name }}"
    - build-essential
